### ISSUE TITLE
Improve custom sniffer process

### ISSUE THREAD

**Issue by krtek4** [liip/TheA11yMachine#13]
It seems to me the process to add custom sniffers could be automated a bit more.

For example it should suffice to provide the directory with the ruleset and we should be able to built it ourselves by running grunt inside the tool.

We could also maybe provide a tool to generate the needed structure with an option to easily extend a current standard.

If a `ruleset.js` file can contain only one standard, it's also redundant to have to name it on the CLI.

Any other thoughts ?

**Comment by Hywan** [comment]
We must consider several things:
* The location of the sniffers,
* The location of the compiled version,
* If errors exist, do something.

I did try to do this without Grunt but the Uglify API is just… ugly! Because we did not have time currently, runnning `grunt --sniffers-…` was fine enought. Obviously, we have to update this process!

**Comment by krtek4** [comment]
My desired "API" : `a11ym --sniffers /my/directory/ --standard MyStandard http://example.org/`

Remove the grunt part :)
